/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "clock.h"
#include "led.h"
#include "dma.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

char source[256] = "DMA Memory 2 Memory Transfer Demo for DESD @ SUNBEAM";
char destination[256] = "";

int main(void)
{
	SystemInit();
	Clock_Setup();
	// Test if clock delay is correct
	LedInit(LED_BLUE);
	for(int i=1; i<=4; i++) {
		LedOn(LED_BLUE);
		DelayMs(500);
		LedOff(LED_BLUE);
		DelayMs(500);
	}

	LedInit(LED_ORANGE);
	Dma_Init_M2M((uint8_t*)destination, (uint8_t*)source, sizeof(source));
	while(dma2_flag == 0) {
		LedBlink(LED_ORANGE, 100);
		DelayMs(100);
	}
	dma2_flag = 0;
	// print destination value on LCD/UART to test
	if(strcmp(source, destination) == 0) {
		// success
		LedInit(LED_GREEN);
		while(dma2_flag == 0) {
			LedBlink(LED_GREEN, 300);
			DelayMs(300);
		}
	}
	else {
		// failed
		LedInit(LED_RED);
		while(dma2_flag == 0) {
			LedBlink(LED_RED, 300);
			DelayMs(300);
		}
	}
	return 0;
}
