/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "led.h"
#include "switch.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	// Set PendSV as lowest priority interrupt (0xFF)
	NVIC_SetPriority(PendSV_IRQn, 0xFF);
	NVIC_EnableIRQ(PendSV_IRQn);
	// Led & Switch Init
	LedInit(LED_BLUE);
	LedInit(LED_ORANGE);
	SwitchInit(SWITCH);
	// Main loop
	while(1) {
		LedBlink(LED_ORANGE, 500);
		DelayMs(500);
	}
	return 0;
}


void PendSV_Handler(void) {
	if(exti0_flag) {
		// Blink the Led
		LedBlink(LED_BLUE, 1000);
		exti0_flag = 0;
	}
}
