/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "led.h"
#include "systick.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define CCLK	16000000

int main(void)
{
	SystemInit();
	// Initialize SysTick to generate interrupt after every 1 ms
	SysTick_Config(CCLK / 1000);
	LedInit(LED_BLUE);
	while(1) {
		LedOn(LED_BLUE);
		SysTick_Delay(5000);
		LedOff(LED_BLUE);
		SysTick_Delay(5000);
	}
	return 0;
}






